### ISSUE TITLE
[1.18.1] Crash shortly after walking around in newly generated world, server closed. (RafflesiaBlockEntity).

### ISSUE THREAD

**Issue by Gbergz** [SnappyDragon18/Habitat#12]
Title ^

**Minecraft**: 1.18.1
**Forge**: 39.0.45
**Habitat**: 1.1.1 | https://www.curseforge.com/minecraft/mc-mods/habitat/files/3562490

**Crash-Report**: https://gist.github.com/Gbergz/d822d945f864bf2ad1d552261421e40b

**Comment by SnappyDragon64** [comment]
Will look into it soon

**Comment by SnappyDragon64** [comment]
[Fixed](https://github.com/SnappyDragon18/Habitat/commit/3e1dc5f4a4ee210120489f78a9df072175c6901e)
